
# use eps greedy act selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000  # 500000 for corr and 3s5z_vs_3s6z



# runner: "parallel"
runner: "episode"
# batch_size_run: 8
buffer_size: 5000
# batch_size_run: 2
t_max: 1050000
breakpoint: 700000



# update the target network every {} episodes
target_update_interval: 200



# use the Q Learner to train
max: "n_mac"
agent: "att_rnn"  # self-attention for communication
agent_output_type: q
att_heads: 4
att_embed_dim: 32
double_q: True
learner: "qplex_learner_teacher"
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64


num_kernel: 4
is_minus_one: True
is_adv_attention: True
is_stop_gradient: True


n_head: 4 # attention head num
attend_reg_coef: 0.001
state_bias: True  # the constant val c(s) in the paper
mask_dead: False
weighted_head: False
nonlinear: False
lamb: 0.02
alpha: 1.0
optimizer: 'adam'
grad_norm_clip: 10.0
use_onehot_loss: True 
evaluate: False
# save_buffer: True
name: "qplex_cadp"